apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: argocd-managedcluster
  namespace: argocd
spec:
  destination:
    name: test-crossplane
    namespace: argocd
  project: default
  source:
    chart: argo-cd
    helm:
      values: |
        configs:
          cmp:
            create: true
            plugins:
              kustomize-sha:
                init:
                  args:
                  - |
                    cd _${ARGOCD_APP_NAME} \
                      && kustomize edit set image \
                        ${REGISTRY}/${ARGOCD_APP_NAME}=${REGISTRY}/${ARGOCD_APP_NAME}:sha-${ARGOCD_APP_REVISION}
                  command:
                  - "/bin/sh"
                  - "-c"
                generate:
                  args:
                  - "kustomize build ${ENVIRONMENT}"
                  command:
                  - "/bin/sh"
                  - "-c"
        controller:
          args:
            appResyncPeriod: 15
        repoServer:
          extraArgs:
          - '--revision-cache-expiration=30s'
          extraContainers:
          - name: kustomize-sha
            command:
              - "/var/run/argocd/argocd-cmp-server"
            image: busybox
            securityContext:
              runAsNonRoot: true
              runAsUser: 999
            volumeMounts:
              - mountPath: /var/run/argocd
                name: var-files
              - mountPath: /home/argocd/cmp-server/plugins
                name: plugins
              # Remove this volumeMount if you've chosen to bake the config file into the sidecar image.
              - mountPath: /home/argocd/cmp-server/config/plugin.yaml
                subPath: kustomize-sha.yaml
                name: argocd-cmp-cm
              # Starting with v2.4, do NOT mount the same tmp volume as the repo-server container. The filesystem separation helps
              # mitigate path traversal attacks.
              - mountPath: /tmp
                name: cmp-tmp
        volumes:
          - name: argocd-cmp-cm
            configMap:
              name: argocd-cmp-cm
          - name: cmp-tmp
            emptyDir: {}
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: "5.26.0"
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
