apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    name: test-crossplane
    namespace: ingress-nginx
  project: default
  source:
    chart: ingress-nginx
    helm:
      values: |
        controller:
          updateStrategy:
            type: "RollingUpdate"
            rollingUpdate:
              maxUnavailable: 1
          terminationGracePeriodSeconds: 0
          watchIngressWithoutClass: true
          publishService:
            enabled: false
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: "4.5.2"
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
