apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: cert-manager
  namespace: argocd
spec:
  destination:
    name: test-crossplane
    namespace: cert-manager
  project: default
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.9.2
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
    chart: cert-manager
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
