apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: kyverno-policies-managedcluster
  namespace: argocd
spec:
  destination:
    name: test-crossplane
    namespace: kyverno
  project: default
  source:
    chart: kyverno-policies
    helm:
      values: |
        includeRestrictedPolicies:
        - require-run-as-nonroot
        - require-run-as-non-root-user
        validationFailureActionByPolicy:
          require-run-as-nonroot: enforce
          require-run-as-non-root-user: enforce
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: "2.6.5"
  syncPolicy:
    automated: {}
