apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: external-dns-managedcluster
  namespace: argocd
spec:
  destination:
    name: test-crossplane
    namespace: external-dns
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 6.14.1
    helm:
      values: |
        provider: cloudflare
        cloudflare:
          proxied: false
          secretName: cloudflare-credentials
    chart: external-dns
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
