apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress-nginx
    helm:
      values: |
        controller:
          updateStrategy:
            type: "RollingUpdate"
            rollingUpdate:
              maxUnavailable: 1
          hostPort:
            enabled: true
          terminationGracePeriodSeconds: 0
          service:
            type: "NodePort"
          watchIngressWithoutClass: true
          nodeSelector:
            ingress-ready: "true"
          tolerations:
            - key: "node-role.kubernetes.io/master"
              operator: "Equal"
              effect: "NoSchedule"
          publishService:
            enabled: false
          extraArgs:
            publish-status-address: "localhost"
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: "4.5.2"
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
