---
apiVersion: v1
kind: Secret
metadata:
  name: github-tgdfool2-assessment-reposecret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/tgdfool2/assessment.git
  password: <GITHUB_TOKEN>
  username: tgdfool2
