apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: assessment
  namespace: argocd
spec:
  destination:
    namespace: assessment
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/test-crossplane
    repoURL: https://github.com/tgdfool2/assessment.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
