apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: assessment
  namespace: argocd
spec:
  destination:
    namespace: assessment
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./k8s
    plugin:
      env:
      - name: ENVIRONMENT
        value: test-crossplane
      - name: REGISTRY
        value: ghcr.io/tgdfool2
      name: kustomize-sha
    repoURL: https://github.com/tgdfool2/assessment-dawid.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
