---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: external-dns
  name: external-dns
---
apiVersion: v1
stringData:
  cloudflare_api_token: <CLOUDFLARE_API_TOKEN>
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: external-dns
type: Opaque
