# For external-dns
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: external-dns
  name: external-dns
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: external-dns
stringData:
  cloudflare_api_token: <CLOUDFLARE_API_TOKEN>
type: Opaque

# For cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: cert-manager
  name: cert-manager
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: cert-manager
stringData:
  api-token: <CLOUDFLARE_API_TOKEN>
type: Opaque
