---
apiVersion: azure.crossplane.io/v1alpha3
kind: ResourceGroup
metadata:
  name: test-tgdfool2-rg
spec:
  location: westeurope
---
apiVersion: compute.azure.crossplane.io/v1alpha3
kind: AKSCluster
metadata:
  name: test-tgdfool2-aks
spec:
  location: westeurope
  version: "1.22.4"
  nodeVMSize: Standard_B2s
  resourceGroupNameRef:
    name: test-tgdfool2-rg
  dnsNamePrefix: test-tgdfool2
  nodeCount: 1
