apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: crossplane
  namespace: argocd
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: crossplane/crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: "1.11.1"
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
