---
apiVersion: kubernetes.do.crossplane.io/v1alpha1
kind: DOKubernetesCluster
metadata:
  name: test-crossplane
spec:
  providerConfigRef:
    name: do-provider
  forProvider:
    region: fra1
    version: 1.25.4-do.0
    tags:
      - test-crossplane
    nodePools:
      - size: s-1vcpu-2gb
        count: 1
        name: worker-pool
    #maintenancePolicy:
    #  startTime: "00:00"
    #  day: wednesday
    #autoUpgrade: true
    #surgeUpgrade: false
    highlyAvailable: false
