---
apiVersion: cluster.civo.crossplane.io/v1alpha1
kind: CivoKubernetes
metadata:
  name: test-crossplane
spec:
  applications: []
  connectionDetails:
    connectionSecretNamePrefix: creds
    connectionSecretNamespace: crossplane-system
  name: test-crossplane
  pools:
  - count: 2
    size: g4s.kube.small
  version: "1.23.6-k3s1"
